# Site settings
title: Tejashree Chhajed
email: hello@tejashree.de
description: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc blandit mattis nulla eu cursus. Fusce finibus, orci sit amet tincidunt fermentum, risus ante pharetra nisi, eget tempus tellus tellus ut est.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.tejashree.de" # the base hostname & protocol for your site
twitter_username: tjchhajed
github_username:  tjchhajed

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
job.title: "Java Developer"
excerpt_separator: "<!--more-->"

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""
