url: http://www.tejashree.de
baseurl: #

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 33ccff
  secondary: 33ccf1
  secondary-dark: 333

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  # - title: twitter
  #   url: http://twitter.com/surajroland
  # - title: facebook
  #   url:
  # - title: stack-overflow
  #   url:
  # - title: bitbucket
  #   url: http://bitbucket.org/surajroland
  - title: linkedin
    url: https://www.linkedin.com/in/tejashree-chhajed/
  - title: skype
    url: skype://tjchhajed?call
  - title: github
    url: http://github.com/tjchhajed


# Build settings
markdown: kramdown
permalink: pretty
